const FusionReactorMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.electric.FusionReactorMachine")

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('uhv_fusion_reactor', 'multiblock').machine((holder) => new FusionReactorMachine(holder, GTValues.UHV))
        .rotationState(RotationState.ALL)
        .recipeTypes(GTRecipeTypes.FUSION_RECIPES)
        .noRecipeModifier()
        .appearanceBlock(() => Block.getBlock('kubejs:fusion_casing_mk4'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('###############', '######GBG######', '###############')
            .aisle('######FCF######', '####BB###BB####', '######FCF######')
            .aisle('####CC###CC####', '###E##GBG##E###', '####CC###CC####')
            .aisle('###C#######C###', '##EAEB###BEAE##', '###C#######C###')
            .aisle('##C#########C##', '#B#E#######E#B#', '##C#########C##')
            .aisle('##C#########C##', '#B#B#######B#B#', '##C#########C##')
            .aisle('#F###########F#', 'G#G#########G#G', '#F###########F#')
            .aisle('#C###########C#', 'B#B#########B#B', '#C###########C#')
            .aisle('#F###########F#', 'G#G#########G#G', '#F###########F#')
            .aisle('##C#########C##', '#B#B#######B#B#', '##C#########C##')
            .aisle('##C#########C##', '#B#E#######E#B#', '##C#########C##')
            .aisle('###C#######C###', '##EAEB###BEAE##', '###C#######C###')
            .aisle('####CC###CC####', '###E##GBG##E###', '####CC###CC####')
            .aisle('######FCF######', '####BB###BB####', '######FCF######')
            .aisle('###############', '######G@G######', '###############')
            .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            .where('E', Predicates.blocks('gtceu:uhv_energy_input_hatch').setPreviewCount(16))
            .where('B', Predicates.blocks('kubejs:fusion_glass_mk2')
                .or(Predicates.blocks('kubejs:fusion_casing_mk4')))
            .where('A', Predicates.blocks('kubejs:fusion_coil_mk2'))
            .where("C", Predicates.blocks('kubejs:fusion_casing_mk4')
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
            )
            .where("F", Predicates.blocks('kubejs:fusion_casing_mk4')
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
            )
            .where("G", Predicates.blocks('kubejs:fusion_casing_mk4')
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMinGlobalLimited(16))
            )
            .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel("kubejs:block/fusion/fusion_casing_mk4", 'gtceu:block/multiblock/fusion_reactor')
})