const $SteamMulti = Java.loadClass('com.gregtechceu.gtceu.common.machine.multiblock.steam.SteamParallelMultiblockMachine');
GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('steam_fusion_reactor', 'multiblock').machine((holder) => new $SteamMulti(holder, 8))
        .rotationState(RotationState.ALL)
        .recipeTypes('steam_fusion_reactor')
        .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
        .appearanceBlock(GCYMBlocks.CASING_INDUSTRIAL_STEAM)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('###############', '######GBG######', '###############')
            .aisle('######FCF######', '####BB###BB####', '######FCF######')
            .aisle('####CC###CC####', '###E##GBG##E###', '####CC###CC####')
            .aisle('###C#######C###', '##EAEB###BEAE##', '###C#######C###')
            .aisle('##C#########C##', '#B#E#######E#B#', '##C#########C##')
            .aisle('##C#########C##', '#B#B#######B#B#', '##C#########C##')
            .aisle('#F###########F#', 'G#G#########G#G', '#F###########F#')
            .aisle('#C###########C#', 'B#B#########B#B', '#C###########C#')
            .aisle('#F###########F#', 'G#G#########G#G', '#F###########F#')
            .aisle('##C#########C##', '#B#B#######B#B#', '##C#########C##')
            .aisle('##C#########C##', '#B#E#######E#B#', '##C#########C##')
            .aisle('###C#######C###', '##EAEB###BEAE##', '###C#######C###')
            .aisle('####CC###CC####', '###E##GBG##E###', '####CC###CC####')
            .aisle('######FCF######', '####BB###BB####', '######FCF######')
            .aisle('###############', '######G@G######', '###############')
            .where('@', Predicates.controller(Predicates.blocks(definition.get())))
            .where('E', Predicates.blocks('gtceu:industrial_steam_casing')
                .or(Predicates.abilities(PartAbility.STEAM)).setMinGlobalLimited(1))
            .where('B', Predicates.blocks('gtceu:tempered_glass'))
            .where('A', Predicates.blocks('gtceu:cupronickel_coil_block'))
            .where("C", Predicates.blocks('gtceu:industrial_steam_casing'))
            .where("F", Predicates.blocks('gtceu:industrial_steam_casing')
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMinGlobalLimited(2))
            )
            .where("G", Predicates.blocks('gtceu:industrial_steam_casing')
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMinGlobalLimited(1))
            )
            .where('#', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/gcym/industrial_steam_casing', 'gtceu:block/multiblock/fusion_reactor')

        
})

GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('steam_fusion_reactor')
        .category('fusion_reactor')
        .setEUIO('in')
        .setMaxIOSize(0, 0, 2, 1)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_FUSION, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COMBUSTION)
})