ServerEvents.recipes(event => {
    event.recipes.gtceu.assembly_line(('steve_cell'))
        .itemInputs('minecraft:player_head', 'minecraft:netherite_helmet', 'minecraft:netherite_chestplate', 'minecraft:netherite_leggings', 'minecraft:netherite_boots', 'minecraft:totem_of_undying', '32x gtceu:meat_dust', '16x gtceu:enriched_nether_quartz_gem')
        .itemOutputs('64x kubejs:steve_cell')
        .inputFluids('minecraft:lava 64000')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LuV])
            ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Item.of('minecraft:player_head')).EUt(5237).duration(10000))

            //will move to amino_forge
    event.recipes.gtceu.large_chemical_reactor(('alanine'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('3x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 7000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:alanine_dust')
        .circuit(1)
        .duration(520)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('arginine'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('6x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 14000', 'gtceu:nitrogen 4000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:arginine_dust')
        .circuit(2)
        .duration(1040)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('asparagine'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('4x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 8000', 'gtceu:nitrogen 2000', 'gtceu:oxygen 3000')
        .itemOutputs('gtceu:asparagine_dust')
        .circuit(3)
        .duration(680)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('aspartic_acid'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('4x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 7000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 4000')
        .itemOutputs('gtceu:aspartic_acid_dust')
        .circuit(4)
        .duration(640)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('cysteine'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('3x gtceu:carbon_dust', 'gtceu:sulfur_dust')
        .inputFluids('gtceu:hydrogen 7000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:cysteine_dust')
        .circuit(5)
        .duration(560)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('glutamic_acid'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('5x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 9000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 4000')
        .itemOutputs('gtceu:glutamic_acid_dust')
        .circuit(6)
        .duration(760)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('glutamine'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('5x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 10000', 'gtceu:nitrogen 2000', 'gtceu:oxygen 3000')
        .itemOutputs('gtceu:glutamine_dust')
        .circuit(7)
        .duration(800)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('glycine'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('2x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 5000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:glycine_dust')
        .circuit(8)
        .duration(400)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('histidine'))
        .itemInputs('6x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 9000', 'gtceu:nitrogen 3000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:histidine_dust')
        .circuit(9)
        .duration(800)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.large_chemical_reactor(('isoleucine'))
        .itemInputs('6x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 13000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:histidine_dust')
        .circuit(10)
        .duration(880)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.large_chemical_reactor(('leucine'))
        .itemInputs('6x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 13000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:leucine_dust')
        .circuit(11)
        .duration(880)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.large_chemical_reactor(('lysine'))
        .itemInputs('6x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 14000', 'gtceu:nitrogen 2000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:lysine_dust')
        .circuit(12)
        .duration(960)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.large_chemical_reactor(('methionine'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('5x gtceu:carbon_dust', 'gtceu:sulfur_dust')
        .inputFluids('gtceu:hydrogen 11000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:methionine_dust')
        .circuit(13)
        .duration(800)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('phenylalanine'))
        .itemInputs('9x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 11000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:phenylalanine_dust')
        .circuit(14)
        .duration(920)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.large_chemical_reactor(('proline'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('5x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 9000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:proline_dust')
        .circuit(15)
        .duration(680)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('serine'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('3x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 7000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 3000')
        .itemOutputs('gtceu:serine_dust')
        .circuit(16)
        .duration(560)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('threonine'))
        .itemInputs('4x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 9000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 3000')
        .itemOutputs('gtceu:threonine_dust')
        .circuit(17)
        .duration(680)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.large_chemical_reactor(('tryptophan'))
        .itemInputs('11x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 12000', 'gtceu:nitrogen 2000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:tryptophan_dust')
        .circuit(18)
        .duration(1080)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.large_chemical_reactor(('tyrosine'))
        .chancedInput('kubejs:steve_cell', 2000, 0)
        .itemInputs('9x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 11000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 3000')
        .itemOutputs('gtceu:tyrosine_dust')
        .circuit(19)
        .duration(960)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.large_chemical_reactor(('valine'))
        .itemInputs('5x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 11000', 'gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .itemOutputs('gtceu:valine_dust')
        .circuit(20)
        .duration(760)
        .EUt(GTValues.VA[GTValues.LuV])
    }
)