ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_reactor(('lead_nitrate_dust'))
        .itemInputs('2x gtceu:massicot_dust')
        .itemOutputs('7x gtceu:lead_nitrate_dust')
        .inputFluids('gtceu:nitric_acid 2000')
        .outputFluids('minecraft:water 1000')
        .duration(75)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor(('thiocyanic_acid'))
        .itemInputs('7x gtceu:lead_nitrate_dust')
        .chancedOutput('gtceu:lead_dust', 8500, 0)
        .chancedOutput('gtceu:sulfur_dust', 6500, 0)
        .inputFluids('gtceu:hydrogen_sulfide 1000')
        .outputFluids('gtceu:thiocyanic_acid 2000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.dehydrator(('low_quality_blaze_dust'))
        .itemOutputs('gtceu:sulfur_dust', '3x gtceu:low_quality_blaze_dust')
        .inputFluids('gtceu:thiocyanic_acid 2000')
        .duration(160)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.mixer(('low_quality_blaze_powder_mixture'))
        .itemInputs('4x gtceu:low_quality_blaze_dust')
        .chancedOutput('gtceu:ash_dust', 1500, 0)
        .outputFluids('gtceu:low_quality_blaze_powder_mixture 1000')
        .inputFluids('gtceu:steam 5000')
        .duration(280)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.electric_blast_furnace(('blast_blaze_powder'))
        .itemInputs('3x gtceu:low_quality_blaze_dust')
        .itemOutputs('minecraft:blaze_powder')
        .chancedOutput('gtceu:ash_dust', 1000, 0)
        .inputFluids('gtceu:naphtha 1500')
        .circuit(1)
        .blastFurnaceTemp(2000)
        .duration(800)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.canner(('ender_eye'))
        .itemInputs('kubejs:ender_pearl_case')
        .itemOutputs('minecraft:ender_eye')
        .inputFluids('gtceu:low_quality_blaze_powder_mixture 1000')
        .duration(600)
        .EUt(GTValues.VA[GTValues.MV])
    }
)