ServerEvents.recipes(event => {
    event.recipes.gtceu.canner(('ender_pearl'))
        .itemInputs('kubejs:ender_pearl_case')
        .itemOutputs('minecraft:ender_pearl')
        .inputFluids('gtceu:green_dye 288')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.alloy_smelter(('ender_pearl_case'))
        .notConsumable('gtceu:ball_casting_mold')
        .itemInputs('8x gtceu:low_quality_ender_pearl_dust')
        .itemOutputs('kubejs:ender_pearl_case')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
    
    event.recipes.gtceu.chemical_reactor(('low_quality_ender_pearl_dust'))
        .itemInputs('6x gtceu:potash_dust', '7x gtceu:beryllium_azide_dust')
        .itemOutputs('14x gtceu:low_quality_ender_pearl_dust')
        .inputFluids('gtceu:hydrochloric_acid 1000')
        .duration(900)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('beryllium_chloride_dust'))
        .itemInputs('gtceu:beryllium_dust')
        .itemOutputs('3x gtceu:beryllium_chloride_dust')
        .inputFluids('gtceu:chlorine 2000')
        .duration(60)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('beryllium_azide_dust'))
        .itemInputs('3x gtceu:beryllium_chloride_dust', '8x gtceu:ice_dust')
        .itemOutputs('7x gtceu:beryllium_azide_dust', '2x gtceu:silicon_dioxide_dust')
        .inputFluids('gtceu:trimethylsilyl_azide 2000')
        .outputFluids('gtceu:dimethyldichlorosilane 1000', 'gtceu:methane 1000')
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('trimethylsilyl_azide'))
        .itemInputs('4x gtceu:sodium_azide_dust')
        .itemOutputs('2x gtceu:salt_dust')
        .inputFluids('gtceu:trimethylchlorosilane 1000')
        .outputFluids('gtceu:trimethylsilyl_azide 1000')
        .duration(80)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('sodium_azide_dust'))
        .itemInputs('4x gtceu:sodium_nitrite_dust')
        .itemOutputs('4x gtceu:sodium_azide_dust')
        .inputFluids('gtceu:nitric_oxide 2000', 'gtceu:methane 1000')
        .outputFluids('minecraft:water 2000')
        .duration(320)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('sodium_nitrite_dust'))
        .itemInputs('6x gtceu:soda_ash_dust')
        .itemOutputs('4x gtceu:sodium_nitrite_dust')
        .inputFluids('gtceu:nitric_oxide 1000', 'gtceu:nitrogen_dioxide 1000')
        .outputFluids('gtceu:carbon_dioxide 1000')
        .duration(180)
        .EUt(GTValues.VA[GTValues.LV])

    event.remove({ id: 'gtceu:chemical_reactor/dimethylchlorosilane_from_chloromethane' })
    event.remove({ id: 'gtceu:large_chemical_reactor/dimethylchlorosilane_from_chloromethane' })
    event.recipes.gtceu.chemical_reactor(('trimethylchlorosilane'))
        .itemInputs('3x gtceu:silicon_dust')
        .inputFluids('gtceu:chloromethane 6000')
        .outputFluids('gtceu:trimethylchlorosilane 1000', 'gtceu:dimethyldichlorosilane 1000', 'gtceu:methyltrichlorosilane 1000')
        .duration(1440)
        .EUt(GTValues.VA[GTValues.LV])
    }
    
)