ServerEvents.recipes(event => {
    event.recipes.gtceu.alloy_smelter(('copper_gold_mixture_ingot'))
        .itemInputs('gtceu:gold_metal_mixture_dust', '3x gtceu:annealed_copper_plate')
        .itemOutputs('4x gtceu:copper_gold_mixture_ingot')
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('gold_leach_dust'))
        .itemInputs('4x gtceu:copper_gold_mixture_ingot')
        .inputFluids('gtceu:nitric_acid 1000')
        .itemOutputs('4x gtceu:gold_leach_dust')
        .outputFluids('gtceu:nitrogen_dioxide 1000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.LV])

    event.remove({ id: 'gtceu:large_chemical_reactor/nitrogen_dioxide_from_elements' })
    event.recipes.gtceu.chemical_reactor(('nitrogen_dioxide'))
        .inputFluids('gtceu:nitrogen 1000', 'gtceu:oxygen 2000')
        .outputFluids('gtceu:nitrogen_dioxide 1000')
        .circuit(3)
        .duration(160)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('chloroauric_acid'))
        .itemInputs('4x gtceu:gold_leach_dust')
        .inputFluids('gtceu:hydrochloric_acid 1000')
        .itemOutputs('4x gtceu:leached_copper_dust')
        .outputFluids('gtceu:chloroauric_acid 1000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('gold_dust'))
        .notConsumable('gtceu:potassium_sulfate_dust')
        .inputFluids('gtceu:chloroauric_acid 1000', 'gtceu:distilled_water 750')
        .itemOutputs('2x gtceu:gold_dust')
        .outputFluids('minecraft:water 1500', 'gtceu:chlorine 1000')
        .duration(100)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('potassium_sulfate_dust'))
        .itemInputs('2x gtceu:potassium_dust', 'gtceu:sulfur_dust')
        .inputFluids('gtceu:oxygen 4000')
        .itemOutputs('7x gtceu:potassium_sulfate_dust')
        .duration(164)
        .EUt(GTValues.VA[GTValues.LV])
    event.remove({ id: 'gtceu:chemical_reactor/potassium_pyrosulfate_dust' })
    event.remove({ id: 'gtceu:large_chemical_reactor/potassium_pyrosulfate_dust' })
    event.recipes.gtceu.chemical_reactor(('potassium_pyrosulfate_dust'))
        .itemInputs('7x gtceu:potassium_sulfate_dust', 'gtceu:sulfur_dust')
        .inputFluids('gtceu:oxygen 3000')
        .itemOutputs('11x gtceu:potassium_pyrosulfate_dust')
        .duration(44)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.sifter(('copper_dust')) //will change to dehydrator
        .itemInputs('gtceu:leached_copper_dust')
        .chancedOutput('gtceu:copper_dust', 7500, 0)
        .chancedOutput('gtceu:silver_dust', 2000, 0)
        .chancedOutput('gtceu:iron_dust', 1000, 0)
        .chancedOutput('gtceu:lead_dust', 1000, 0)
        .chancedOutput('gtceu:nickel_dust', 500, 0)
        .duration(80)
        .EUt(GTValues.VA[GTValues.LV])
    }
)