ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_plant(('netherrack_slurry'))
        .itemInputs('64x gtceu:netherrack_dust')
        .chancedOutput('20x gtceu:sulfur_dust', 1500, 0)
        .chancedOutput('8x minecraft:glowstone_dust', 500, 0)
        .chancedOutput('8x gtceu:coal_dust', 500, 0)
        .chancedOutput('2x gtceu:gold_dust', 200, 0)
        .inputFluids('minecraft:lava 8000', 'gtceu:sulfuric_acid 2000', 'gtceu:carbon_monoxide 10000')
        .outputFluids('gtceu:netherrack_slurry 100000')
        .addCondition(GTNNRecipes.setPlantCasing(6))
        .duration(3200)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.brewery(('shine_netherrack_slurry'))
        .itemInputs('gtceu:tiny_nether_star_dust')
        .inputFluids('gtceu:netherrack_slurry 4000')
        .outputFluids('gtceu:shine_netherrack_slurry 4000')
        .duration(80)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.distillation_tower(('heavy_light_netherrack_slurry'))
        .inputFluids('gtceu:shine_netherrack_slurry 16000')
        .chancedOutput('gtceu:zincite_dust', 1500, 0)
        .outputFluids('gtceu:light_netherrack_slurry 10000', 'gtceu:heavy_netherrack_slurry 6000', 'gtceu:netherrack_waste 2000')
        .duration(480)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.fusion_reactor(('metallic_heavy_netherrack_slurry'))
        .inputFluids('gtceu:heavy_netherrack_slurry 125', 'gtceu:rhodium 2')
        .outputFluids('gtceu:metallic_heavy_netherrack_slurry 125')
        .duration(16)
        .EUt(GTValues.VA[GTValues.EV])
        .fusionStartEU(50000000);  

    event.recipes.gtceu.centrifuge(('heavy_netherrack_mixture'))
        .itemOutputs('24x gtceu:heavy_netherrack_metal_mixture_dust', 'gtceu:mysterious_netherrack_mixture_dust')
        .chancedOutput('minecraft:redstone', 800, 0)
        .inputFluids('gtceu:metallic_heavy_netherrack_slurry 1000')
        .outputFluids('gtceu:low_quality_netheritic_slurry 1000', 'gtceu:steam 1000')
        .duration(600)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.time_machine(('netherite_scrap'))
        .itemInputs('4x kubejs:circuit_scrap')
        .itemOutputs('minecraft:netherite_scrap')
        .inputFluids('gtceu:low_quality_netheritic_slurry 1000', 'gtceu:thousand_year_fuel 4000')
        .outputFluids('gtceu:time_residue 400')
        .duration(4000)
        .EUt(GTValues.VA[GTValues.LuV])//fused gold?

    event.recipes.gtceu.electric_blast_furnace(('dry_mysterious_netherrack_mixture_dust'))
        .itemInputs('3x gtceu:mysterious_netherrack_mixture_dust', '5x gtceu:carbon_dust')
        .itemOutputs('3x gtceu:dry_mysterious_netherrack_mixture_dust')
        .inputFluids('gtceu:hydrogen 5000')
        .outputFluids('gtceu:phenol 1000')
        .duration(400)
        .blastFurnaceTemp(4400)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.mixer(('enriched_naquadic_mysterious_netherrack_mixture'))
        .itemInputs('8x gtceu:dry_mysterious_netherrack_mixture_dust')
        .chancedOutput('gtceu:naquadria_oxide_mixture_dust', 4000, 0)
        .inputFluids('gtceu:enriched_naquadah 432')
        .outputFluids('gtceu:enriched_naquadic_mysterious_netherrack_mixture 8000')
        .duration(480)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.electrolyzer(('enriched_mysterious_netherrack_mixture'))
        .itemOutputs('gtceu:naquadah_dust')
        .inputFluids('gtceu:enriched_naquadic_mysterious_netherrack_mixture 4000')
        .outputFluids('gtceu:enriched_mysterious_netherrack_mixture 3600')
        .duration(300)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.distillation_tower(('wriggle_netherrack'))
        .chancedOutput('gtceu:ash_dust', 7500, 0)
        .inputFluids('gtceu:enriched_mysterious_netherrack_mixture 10000')
        .outputFluids('gtceu:enriched_netherrack_crystal_slurry 4000', 'gtceu:wriggle_netherrack 6000', 'gtceu:diluted_netherrack_slurry 2000')
        .duration(1200)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.fluid_solidifier(('enriched_nether_quartz_gem'))
        .itemInputs('gtceu:exquisite_nether_quartz_gem')
        .itemOutputs('gtceu:enriched_nether_quartz_gem')
        .inputFluids('gtceu:enriched_netherrack_crystal_slurry 1000')
        .duration(80)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor(('salty_wriggle_netherrack'))
        .itemInputs('3x gtceu:rock_salt_dust', 'gtceu:salt_dust')
        .inputFluids('gtceu:wriggle_netherrack 1000')
        .outputFluids('gtceu:salty_wriggle_netherrack 1000')
        .duration(150)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.fluid_solidifier(('salty_wriggle_netherrack_doped_tear'))
        .itemInputs('minecraft:ghast_tear')
        .itemOutputs('kubejs:salty_wriggle_netherrack_doped_tear')
        .inputFluids('gtceu:salty_wriggle_netherrack 1000')
        .duration(400)
        .EUt(GTValues.VA[GTValues.MV])
        
    event.recipes.gtceu.canner(('soul_netherrack_tear_mixture'))
        .itemInputs('4x minecraft:soul_sand', 'kubejs:salty_wriggle_netherrack_doped_tear')
        .itemOutputs('4x minecraft:soul_soil')
        .outputFluids('gtceu:soul_netherrack_tear_mixture 1000')
        .duration(640)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor(('lava_oozed_soul_netherrack_tear_mixture'))
        .itemOutputs('2x gtceu:stone_dust')
        .inputFluids('gtceu:soul_netherrack_tear_mixture 1250')
        .perTick(true)
        .inputFluids('minecraft:lava 5')//bugged, it will fix next update
        .perTick(false)
        .outputFluids('gtceu:lava_oozed_soul_netherrack_tear_mixture 1000')
        .duration(2000)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.electric_blast_furnace(('crying_obsidian'))
        .itemInputs('minecraft:obsidian', '2x minecraft:amethyst_shard')
        .itemOutputs('minecraft:crying_obsidian')
        .inputFluids('gtceu:lava_oozed_soul_netherrack_tear_mixture 1000')
        .duration(980)
        .blastFurnaceTemp(4949)
        .EUt(GTValues.VA[GTValues.ZPM])

    event.recipes.gtceu.electromagnetic_separator(('magnetic_separated_heavy_netherrack_metal_mixture_dust'))
        .itemInputs('3x gtceu:heavy_netherrack_metal_mixture_dust')
        .itemOutputs('3x gtceu:magnetic_separated_heavy_netherrack_metal_mixture_dust')
        .chancedOutput('2x gtceu:small_magnetic_neodymium_dust', 1000, 0)
        .chancedOutput('gtceu:tiny_magnetic_samarium_dust', 500, 0)
        .duration(320)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.fusion_reactor(('radium'))
        .inputFluids('gtceu:iridium 16', 'gtceu:silicon 16')
        .outputFluids('gtceu:radium 125')
        .duration(32)
        .EUt(GTValues.VA[GTValues.IV])
        .fusionStartEU(55000000);  

    event.recipes.gtceu.laser_engraver(('irradiated_heavy_netherrack_metal_mixture_dust'))
        .notConsumable('gtceu:monazite_lens')
        .itemInputs('2x gtceu:magnetic_separated_heavy_netherrack_metal_mixture_dust')
        .itemOutputs('2x gtceu:irradiated_heavy_netherrack_metal_mixture_dust')
        .duration(36)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.neutron_activator(('radioactive_helllium_rare_earth_compound_dust'))
        .inputFluids('gtceu:radium 500')
        .outputFluidsRanged('gtceu:radon', 86, 222)
        .itemInputs('4x gtceu:irradiated_heavy_netherrack_metal_mixture_dust')
        .itemOutputs('4x gtceu:radioactive_helllium_rare_earth_compound_dust')
        .chancedOutput('gtceu:uranium_dust', 600, 0)
        .duration(4000)
        .addCondition(GTNNRecipes.setNA(800, 700))

    event.recipes.gtceu.centrifuge(('helllium_plutonium_lead_scandium_boron_carbon_sulfur_radon_mixture_dust'))
        .itemInputs('32x gtceu:radioactive_helllium_rare_earth_compound_dust')
        .itemOutputs('30x gtceu:helllium_plutonium_lead_scandium_boron_carbon_sulfur_radon_mixture_dust', '2x gtceu:rare_earth_dust')
        .chancedOutput('gtceu:technetium_dust', 1500, 0)
        .chancedOutput('gtceu:plutonium_dust', 600, 0)
        .inputFluids('gtceu:hydrofluoric_acid 500')
        .outputFluids('gtceu:radon 80')
        .duration(180)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor(('helllium_plutonium_lead_scandium_radon_oxygen_mixture_dust'))
        .itemInputs('30x gtceu:helllium_plutonium_lead_scandium_boron_carbon_sulfur_radon_mixture_dust')
        .itemOutputs('23x gtceu:helllium_plutonium_lead_scandium_radon_oxygen_mixture_dust', '3x gtceu:boron_trioxide_dust')
        .inputFluids('gtceu:oxygen 18000')
        .outputFluids('gtceu:carbon_dioxide 1000', 'gtceu:sulfur_trioxide 1000')
        .duration(100)
        .EUt(GTValues.VA[GTValues.HV])
        
    event.recipes.gtceu.chemical_reactor(('helllium_scandium_radon_oxygen_iodine_mixture_dust'))
        .itemInputs('23x gtceu:helllium_plutonium_lead_scandium_radon_oxygen_mixture_dust', '10x gtceu:iodine_dust')
        .itemOutputs('17x gtceu:helllium_scandium_radon_oxygen_iodine_mixture_dust', '3x gtceu:plutonium_iodide_dust', '3x gtceu:lead_iodide_dust')
        .duration(200)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor(('helllium_radon_oxygen_bromine_iodine_mixture_dust'))
        .itemInputs('17x gtceu:helllium_scandium_radon_oxygen_iodine_mixture_dust')
        .itemOutputs('18x gtceu:helllium_radon_oxygen_bromine_iodine_mixture_dust', '4x gtceu:scandium_bromide_dust')
        .inputFluids('gtceu:bromine 6000')
        .duration(400)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.electric_blast_furnace(('scandium_chloride_dust'))
        .itemInputs('4x gtceu:scandium_bromide_dust')
        .itemOutputs('4x gtceu:scandium_chloride_dust')
        .inputFluids('gtceu:salt_water 3000')
        .outputFluids('gtceu:wet_bromine 3000')
        .duration(500)
        .blastFurnaceTemp(3200)
        .EUt(GTValues.VA[GTValues.IV])
    
    event.recipes.gtceu.chemical_reactor(('scandium_hydroxide_dust'))
        .itemInputs('4x gtceu:scandium_chloride_dust', '9x gtceu:sodium_hydroxide_dust')
        .itemOutputs('4x gtceu:scandium_hydroxide_dust', '6x gtceu:salt_dust')
        .duration(200)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.electric_blast_furnace(('scandium_dust'))
        .itemInputs('4x gtceu:scandium_hydroxide_dust', 'gtceu:carbon_dust')
        .itemOutputs('gtceu:scandium_dust')
        .outputFluids('gtceu:carbon_dioxide 1000')
        .duration(1120)
        .blastFurnaceTemp(3109)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.chemical_plant(('helllium_oxygen_bromic_iodide_dust'))
        .itemInputs('18x gtceu:helllium_radon_oxygen_bromine_iodine_mixture_dust', '2x gtceu:low_quality_ender_pearl_dust', 'gtceu:low_quality_blaze_dust')
        .itemOutputs('17x gtceu:helllium_oxygen_bromic_iodide_dust', '4x gtceu:quantum_eye')
        .duration(1800)
        .addCondition(GTNNRecipes.setPlantCasing(6))
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.chemical_reactor(('helllium_trifluoride_dust'))
        .itemInputs('17x gtceu:helllium_oxygen_bromic_iodide_dust')
        .itemOutputs('8x gtceu:helllium_trifluoride_dust', '15x gtceu:iodyl_fluoride_dust')
        .inputFluids('gtceu:fluorine 42000', 'gtceu:ice 2000')
        .outputFluids('gtceu:oxygen_difluoride 7000', 'gtceu:bromyl_fluoride 1000')
        .duration(400)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor(('helllium_tetrafluoride_dust'))
        .itemInputs('4x gtceu:helllium_trifluoride_dust')
        .itemOutputs('6x gtceu:helllium_tetrafluoride_dust')
        .inputFluids('gtceu:hydrofluoric_acid 2000')
        .outputFluids('gtceu:hydrogen 2000')
        .duration(1500)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor(('potassium_fluoride_dust'))
        .itemInputs('6x gtceu:potassium_carbonate_dust')
        .itemOutputs('4x gtceu:potassium_fluoride_dust')
        .inputFluids('gtceu:hydrofluoric_acid 4000')
        .outputFluids('gtceu:fluorine 2000', 'gtceu:carbon_dioxide 1000', 'minecraft:water 1000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor(('dioxygenyl_hexafluoroplatinate_dust'))
        .itemInputs('2x gtceu:platinum_dust')
        .itemOutputs('18x gtceu:dioxygenyl_hexafluoroplatinate_dust')
        .inputFluids('gtceu:oxygen_difluoride 6000', 'gtceu:steam 1000')
        .outputFluids('gtceu:oxygen 2000', 'minecraft:water 16')
        .duration(90)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.chemical_reactor(('bromine_trifluoride'))
        .notConsumable('20x gtceu:mysterious_netherrack_mixture_dust')
        .inputFluids('gtceu:bromyl_fluoride 3000')
        .outputFluids('gtceu:bromine_trifluoride 1000', 'gtceu:bromine 2000', 'gtceu:oxygen 6000')
        .duration(90)
        .EUt(GTValues.VA[GTValues.LuV])//exchanger

        event.recipes.gtceu.fusion_reactor(('selenium'))
        .inputFluids('gtceu:silicon 16', 'gtceu:neon 125')
        .outputFluids('gtceu:selenium 125')
        .duration(80)
        .EUt(GTValues.VA[GTValues.EV])
        .fusionStartEU(45000000);  


    event.recipes.gtceu.chemical_reactor(('selenium_tetrafluoride_dust'))
        .itemInputs('gtceu:selenium_dust')
        .itemOutputs('5x gtceu:selenium_tetrafluoride_dust')
        .inputFluids('gtceu:fluorine 4000')
        .duration(60)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.chemical_reactor(('iodine_pentafluoride_dust'))
        .itemInputs('20x gtceu:iodyl_fluoride_dust', '20x gtceu:selenium_tetrafluoride_dust')
        .itemOutputs('30x gtceu:iodine_pentafluoride_dust', '16x gtceu:seleninyl_fluoride_dust')
        .inputFluids('gtceu:bromine_trifluoride 4000')
        .outputFluids('gtceu:bromine 4000', 'gtceu:oxygen 6000')
        .duration(270)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.electrolyzer(('decomposition_electrolyzing_selenyl_fluoride_fix'))
        .itemInputs('4x gtceu:seleninyl_fluoride_dust')
        .itemOutputs('gtceu:selenium_dust')
        .outputFluids('gtceu:oxygen_difluoride 1000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.large_chemical_reactor(('helllium_heptafluoride_dust'))
        .itemInputs('6x gtceu:helllium_tetrafluoride_dust', '18x gtceu:dioxygenyl_hexafluoroplatinate_dust', '4x gtceu:potassium_fluoride_dust')
        .itemOutputs('8x gtceu:helllium_heptafluoride_dust', '16x gtceu:potassium_hexafluoroplatinate_dust')
        .outputFluids('gtceu:oxygen 4000')
        .duration(800)
        .EUt(GTValues.VA[GTValues.ZPM])

    event.recipes.gtceu.chemical_reactor(('exchanged_light_netherrack_slurry'))
        .inputFluids('gtceu:light_netherrack_slurry 8000', 'gtceu:aqua_gas 1000')
        .outputFluids('gtceu:exchanged_light_netherrack_slurry 8000', 'gtceu:ignis_gas 1000')
        .duration(160)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.mixer(('poor_metal_mixuture_dust'))
        .inputFluids('gtceu:exchanged_light_netherrack_slurry 1000')
        .itemInputs('4x gtceu:rare_earth_dust')
        .itemOutputs('4x gtceu:poor_metal_mixture_dust')
        .duration(320)
        .EUt(GTValues.VA[GTValues.IV])//WIPWIPWIP

    event.recipes.gtceu.electric_blast_furnace(('zincite_poor_metal_mixture_dust'))
        .inputFluids('gtceu:oxygen 6000')
        .itemInputs('6x gtceu:poor_metal_mixture_dust')
        .itemOutputs('4x gtceu:zincite_poor_metal_mixture_dust')
        .outputFluids('gtceu:zinc_exhaust 1000')
        .duration(240)
        .blastFurnaceTemp(4500)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.centrifuge(('zinc_residue_dust'))
        .inputFluids('gtceu:zinc_exhaust 3000')
        .itemOutputs('gtceu:dark_ash_dust', 'gtceu:zinc_residue_dust')//WIP----------------------------
        .outputFluids('gtceu:carbon_dioxide 1000', 'gtceu:sulfur_dioxide 1000')
        .duration(280)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.chemical_bath(('zinc_cadmium_sulfate_dust'))
        .inputFluids('gtceu:sulfuric_acid 1000')
        .itemInputs('gtceu:zinc_residue_dust')
        .itemOutputs('3x gtceu:zinc_cadmium_sulfate_dust')
        .duration(540)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor(('cadmium_thallium_sulfate_solution'))
        .inputFluids('gtceu:mercury 1000')
        .itemInputs('3x gtceu:zinc_cadmium_sulfate_dust')
        .outputFluids('gtceu:cadmium_thallium_sulfate_solution 1000', 'gtceu:zinc_amalgam 1000')
        .duration(280)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.centrifuge(('thallium_residue_dust'))
        .inputFluids('gtceu:cadmium_thallium_sulfate_solution 9000')
        .itemOutputs('gtceu:thallium_residue_dust')
        .outputFluids('gtceu:cadmium_sulfate_solution 9000')
        .duration(330)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.electrolyzer(('cadmium_dust'))
        .inputFluids('gtceu:cadmium_sulfate_solution 9000')
        .itemOutputs('gtceu:cadmium_dust')
        .outputFluids('gtceu:sulfuric_acid 9000')
        .duration(220)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.chemical_reactor(('thallium_sulfate_solution'))
        .inputFluids('minecraft:water 1000', 'gtceu:sulfuric_acid 1000')
        .itemInputs('gtceu:thallium_residue_dust')
        .outputFluids('gtceu:thallium_sulfate_solution 1000')
        .duration(240)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.chemical_reactor(('thallium_chloride_dust'))
        .inputFluids('gtceu:hydrochloric_acid 2000', 'gtceu:thallium_sulfate_solution 1000')
        .itemOutputs('4x gtceu:thallium_chloride_dust')
        .outputFluids('gtceu:sulfuric_acid 1000', 'minecraft:water 1000')
        .duration(460)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.electric_blast_furnace(('thallium_dust'))
        .itemInputs('4x gtceu:thallium_chloride_dust', 'gtceu:zinc_dust')
        .itemOutputs('2x gtceu:thallium_dust', '3x gtceu:zinc_chloride_dust')
        .duration(600)
        .blastFurnaceTemp(2250)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_bath(('germanium_residue_dust'))
        .inputFluids('gtceu:sulfuric_acid 2000')
        .itemInputs('2x gtceu:zincite_poor_metal_mixture_dust')
        .itemOutputs('6x gtceu:zinc_sulfate_dust', 'gtceu:germanium_residue_dust')
        .duration(160)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor(('germanium_acid_solution'))
        .itemInputs('gtceu:germanium_residue_dust')
        .itemOutputs('3x gtceu:aluminium_sulfite_dust')
        .outputFluids('gtceu:germanium_acid_solution 500')
        .duration(200)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor(('germanium_chloride_dust'))
        .inputFluids('gtceu:hydrochloric_acid 4000', 'gtceu:germanium_acid_solution 1000')
        .itemOutputs('5x gtceu:germanium_chloride_dust')
        .duration(260)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.electrolyzer(('germanium_oxide_dust'))//dehydrator??
        .itemInputs('5x gtceu:germanium_chloride_dust')
        .itemOutputs('3x gtceu:germanium_oxide_dust')
        .outputFluids('gtceu:chlorine 4000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.electric_blast_furnace(('germanium_dust'))
        .inputFluids('gtceu:hydrogen 4000')
        .itemInputs('3x gtceu:germanium_oxide_dust')
        .itemOutputs('gtceu:germanium_dust')
        .outputFluids('gtceu:steam 2000')
        .duration(660)
        .blastFurnaceTemp(5200)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.alloy_blast_smelter(('germanium_solder'))
        .itemInputs('23x gtceu:bismuth_dust', '10x gtceu:germanium_dust', '7x gtceu:indium_dust', '6x gtceu:cadmium_dust', '2x gtceu:tin_dust')
        .outputFluids('gtceu:germanium_solder 6912')
        .duration(5800)
        .blastFurnaceTemp(5100)
        .EUt(GTValues.VA[GTValues.IV])






    event.remove({ id: 'gtceu:mixer/naquadah_alloy' })
    event.remove({ id: 'gtceu:centrifuge/decomposition_centrifuging__naquadah_alloy' })
    event.recipes.gtceu.mixer(('naquadah_alloy_netherite'))
        .itemInputs('2x gtceu:naquadah_dust', 'gtceu:osmiridium_dust', '2x gtceu:trinium_dust', '2x gtceu:netherite_dust')
        .itemOutputs('7x gtceu:naquadah_alloy_dust')
        .duration(700)
        .EUt(GTValues.VA[GTValues.IV])
    event.recipes.gtceu.centrifuge(('decomposition_centrifuging__naquadah_alloy_netherite'))
        .itemInputs('7x gtceu:naquadah_alloy_dust')
        .itemOutputs('2x gtceu:naquadah_dust', 'gtceu:osmiridium_dust', '2x gtceu:trinium_dust', '2x gtceu:netherite_dust')
        .duration(2346)
        .EUt(GTValues.VA[GTValues.LV])

    }
)