ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_reactor('polyetherketonetherketoneketone')
        .notConsumable('gtceu:potassium_carbonate_dust')
        .itemInputs('gtceu:tiny_epoxy_dust')
        .inputFluids('gtceu:i_iv_bis_i_iv_fluorobenzoyl_benzene 1000', 'gtceu:iv_ivd_dihydroxybenzophenone 1000')
        .outputFluids('gtceu:polyetherketonetherketoneketone 1008')
        .duration(400)
        .EUt(GTValues.V[GTValues.UHV])

    event.recipes.gtceu.chemical_reactor('i_iv_bis_i_iv_fluorobenzoyl_benzene')
        .itemInputs('gtceu:tiny_aluminium_chloride_dust')
        .inputFluids('gtceu:terephthaloyl_chloride 1000', 'gtceu:fluorobenzene 1000')
        .outputFluids('gtceu:i_iv_bis_i_iv_fluorobenzoyl_benzene 1000')
        .duration(80)
        .EUt(GTValues.V[GTValues.LuV])

    event.recipes.gtceu.fluid_heater('hot_benzenediazonium_tetrafluoroborate')
        .inputFluids('gtceu:benzenediazonium_tetrafluoroborate 500')
        .outputFluids('gtceu:hot_benzenediazonium_tetrafluoroborate 500')
        .duration(72000)
        .EUt(GTValues.V[GTValues.MV])

    event.recipes.gtceu.chemical_reactor('benzenediazonium_tetrafluoroborate')
        .inputFluids('gtceu:benzenediazonium_chloride 1000', 'gtceu:fluoroboric_acid 1000')
        .outputFluids('gtceu:benzenediazonium_tetrafluoroborate 1000', 'gtceu:hydrochloric_acid 1000')
        .duration(60)
        .EUt(GTValues.V[GTValues.LuV])

    event.recipes.gtceu.distillation_tower('fluorobenzene')
        .inputFluids('gtceu:hot_benzenediazonium_tetrafluoroborate 1000')
        .itemOutputs('gtceu:boron_dust')
        .outputFluids('gtceu:fluorobenzene 1000', 'gtceu:fluorine 1500', 'gtceu:nitrogen 1000')
        .duration(360)
        .EUt(GTValues.V[GTValues.IV])

    event.recipes.gtceu.chemical_reactor('benzenediazonium_chloride')
        .itemInputs('gtceu:ice_dust')
        .inputFluids('gtceu:aniline 1000', 'gtceu:nitrous_acid 1000', 'gtceu:hydrochloric_acid 1000')
        .outputFluids('gtceu:benzenediazonium_chloride 1000', 'minecraft:water 2000')
        .duration(800)
        .EUt(GTValues.V[GTValues.ZPM])
    
    event.recipes.gtceu.chemical_reactor('aniline')
        .itemOutputs('gtceu:magnetite_dust')
        .inputFluids('gtceu:nitrobenzene 1000', 'gtceu:iron_ii_chloride 6000', 'gtceu:hydrochloric_acid 6000')
        .outputFluids('gtceu:aniline 1000', 'gtceu:diluted_hydrochloric_acid 4000')
        .duration(160)
        .EUt(GTValues.V[GTValues.EV])

    event.recipes.gtceu.chemical_reactor('fluoroboric_acid')
        .itemInputs('gtceu:boric_acid_dust')
        .inputFluids('gtceu:hydrofluoric_acid 4000')
        .outputFluids('gtceu:fluoroboric_acid 1000', 'minecraft:water 3000')
        .duration(120)
        .EUt(GTValues.V[GTValues.HV])

    event.recipes.gtceu.chemical_reactor('boric_acid')
        .itemInputs('gtceu:borax_dust')
        .inputFluids('gtceu:hydrochloric_acid 2000')
        .itemOutputs('4x gtceu:boric_acid_dust', '2x gtceu:salt_dust')
        .outputFluids('minecraft:water 5000')
        .duration(30)
        .EUt(GTValues.V[GTValues.MV])

    event.recipes.gtceu.chemical_reactor('terephthaloyl_chloride')
        .inputFluids('gtceu:i_iv_bis_trichloromethyl_benzene 1000', 'gtceu:terephthalic_acid 1000')
        .outputFluids('gtceu:terephthaloyl_chloride 2000', 'gtceu:hydrochloric_acid 2000')
        .duration(160)
        .EUt(GTValues.V[GTValues.UV])

    event.recipes.gtceu.chemical_reactor('terephthalic_acid')
        .notConsumable('64x gtceu:double_titanium_plate')
        .itemInputs('gtceu:cobalt_manganese_bromide_dust')
        .inputFluids('gtceu:para_xylene 1000', 'gtceu:acetic_acid 2000', 'gtceu:oxygen 2000')
        .outputFluids('gtceu:terephthalic_acid 1000', 'minecraft:water 2000')
        .duration(900)
        .EUt(GTValues.V[GTValues.EV])

    event.recipes.gtceu.chemical_reactor('cobalt_manganese_bromide')
        .itemInputs('gtceu:cobalt_dust', 'gtceu:manganese_dust')
        .inputFluids('gtceu:hydrobromic_acid 4000')
        .itemOutputs('6x gtceu:cobalt_manganese_bromide_dust')
        .outputFluids('gtceu:hydrogen 4000')
        .duration(70)
        .EUt(GTValues.V[GTValues.LV])

    event.recipes.gtceu.chemical_reactor('hydrobromic_acid')
        .inputFluids('gtceu:hydrogen 1000', 'gtceu:bromine 1000')
        .outputFluids('gtceu:hydrobromic_acid 1000')
        .duration(120)
        .EUt(GTValues.V[GTValues.MV])

    event.recipes.gtceu.chemical_reactor('i_iv_bis_trichloromethyl_benzene')
        .inputFluids('gtceu:dimethylbenzene 1000', 'gtceu:chlorine 6000')
        .outputFluids('gtceu:i_iv_bis_trichloromethyl_benzene 1000')
        .duration(140)
        .EUt(GTValues.V[GTValues.ZPM])


    event.recipes.gtceu.chemical_reactor('iv_ivd_dihydroxybenzophenone')
        .inputFluids('gtceu:iv_hydroxybenzoic_acid 2000')
        .itemOutputs('gtceu:carbon_dust')
        .outputFluids('gtceu:iv_ivd_dihydroxybenzophenone 1000', 'minecraft:water 1000')
        .duration(360)
        .EUt(GTValues.V[GTValues.LuV])

    event.recipes.gtceu.chemical_reactor('iv_hydroxybenzoic_acid')
        .inputFluids('gtceu:sulfuric_acid 1000')
        .itemInputs('gtceu:potassium_phenoxide_dust')
        .outputFluids('gtceu:iv_hydroxybenzoic_acid 1000', 'gtceu:diluted_sulfuric_acid 1000')
        .duration(80)
        .EUt(GTValues.V[GTValues.IV])

    event.recipes.gtceu.chemical_reactor('potassium_phenoxide')
        .inputFluids('gtceu:phenol 1000', 'gtceu:carbon_dioxide 16000')
        .itemInputs('gtceu:potassium_hydroxide_dust')
        .itemOutputs('gtceu:potassium_phenoxide_dust')
        .duration(200)
        .EUt(GTValues.V[GTValues.LV])

    event.recipes.gtceu.brewery('nitrous_acid')
        .inputFluids('gtceu:ammonia 1000')
        .outputFluids('gtceu:nitrous_acid 1000')
        .duration(7200)
        .EUt(GTValues.V[GTValues.MV])


})