ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_plant(('sea_water_solution'))
        .itemInputs('16x gtceu:quartz_sand_dust', '2x minecraft:seagrass')
        .chancedOutput('gtceu:plant_ball', 500, 0)
        .chancedOutput('gtceu:plant_ball', 500, 0)
        .inputFluids('gtceu:salt_water 8000', 'gtceu:ammonia 2000')
        .outputFluids('gtceu:sea_water_solution 16000')
        .addCondition(GTNNRecipes.setPlantCasing(4))
        .duration(3200)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.fluid_heater(('hot_sea_water_solution'))
        .inputFluids('gtceu:sea_water_solution 100')
        .outputFluids('gtceu:hot_sea_water_solution 150')
        .duration(60)
        .circuit(1)
        .EUt(24)

    event.recipes.gtceu.chemical_reactor(('acidic_sea_water_solution'))
        .itemInputs('gtceu:calcium_dust')
        .inputFluids('gtceu:hot_sea_water_solution 2000', 'gtceu:hydrochloric_acid 1000')
        .outputFluids('gtceu:acidic_sea_water_solution 2000')
        .duration(160)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.chemical_plant(('crystaline_sea_water_solution'))
        .itemInputs('3x gtceu:electrotine_dust', 'extendedcrafting:luminessence')
        .itemOutputs('gtceu:silicon_dioxide_dust')
        .inputFluids('gtceu:acidic_sea_water_solution 2000')
        .outputFluids('gtceu:crystaline_sea_water_solution 2000')
        .duration(1000)
        .addCondition(GTNNRecipes.setPlantCasing(5))
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.distillation_tower(('crystaline_sea_water'))
        .chancedOutput('gtceu:calcite_dust', 6000, 0)
        .inputFluids('gtceu:crystaline_sea_water_solution 32000')
        .outputFluids('gtceu:crystaline_sea_water 25000', 'gtceu:salt_water 4000', 'gtceu:crystaline_sea_water_solution 2000', 'gtceu:sea_water_solution 1000')
        .duration(4000)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor(('iodine_crystaline_sea_water'))
        .itemInputs('gtceu:potassium_iodide_dust')
        .inputFluids('gtceu:crystaline_sea_water 1000')
        .outputFluids('gtceu:iodine_crystaline_sea_water 1000')
        .duration(180)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.mixer(('material_crystaline_sea_water'))
        .itemInputs('6x gtceu:stone_dust', 'gtceu:iron_dust', 'gtceu:iron_dust', 'gtceu:iron_dust')
        .inputFluids('gtceu:iodine_crystaline_sea_water 4000')
        .outputFluids('gtceu:material_crystaline_sea_water 5000')
        .duration(2400)
        .EUt(GTValues.VA[GTValues.EV])
        
    event.recipes.gtceu.centrifuge(('aquatic_acid'))
        .inputFluids('gtceu:hydrochloric_acid 1000', 'gtceu:material_crystaline_sea_water 1250')
        .outputFluids('gtceu:aquatic_acid 1000', 'gtceu:material_waste 250', 'gtceu:chlorine 1000')
        .duration(200)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.chemical_plant(('coral_aquatic_solution'))
        .itemInputs('#forge:corals/alive')
        .itemOutputs('gtceu:sulfur_dust')
        .chancedOutput('gtceu:bio_chaff', 1500, 0)
        .inputFluids('gtceu:aquatic_acid 4000', 'gtceu:sulfuric_acid 1000', 'gtceu:oxygen 1000')
        .outputFluids('gtceu:coral_aquatic_solution 4000', 'minecraft:water 1000')
        .duration(800)
        .addCondition(GTNNRecipes.setPlantCasing(4))
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.vacuum_freezer(('cooled_coral_aquatic_solution'))
        .inputFluids('gtceu:coral_aquatic_solution 1000', 'gtceu:liquid_oxygen 100')
        .outputFluids('gtceu:cooled_coral_aquatic_solution 1000', 'gtceu:oxygen 100')
        .duration(40)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.electrolyzer(('low_quality_prismarine_dust'))
        .itemInputs('3x gtceu:tiny_apatite_dust')
        .itemOutputs('3x gtceu:low_quality_prismarine_dust')
        .inputFluids('gtceu:cooled_coral_aquatic_solution 2000', 'gtceu:crystaline_sea_water 1000')
        .outputFluids('gtceu:raw_aquatic_liquid 1000', 'gtceu:nitrogen 500')
        .duration(500)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.cracker(('cracked_aquatic_liquid'))
        .inputFluids('gtceu:raw_aquatic_liquid 1000', 'gtceu:steam 2000')// want to change
        .outputFluids('gtceu:cracked_aquatic_liquid 1000')
        .duration(200)
        .circuit(24)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.electric_blast_furnace(('cobalt_aquate_hydroxide_dust'))
        .itemInputs('2x gtceu:cobalt_dust', '6x gtceu:salt_dust')
        .itemOutputs('7x gtceu:cobalt_aquate_trichloride_dust', '2x gtceu:sodium_hydroxide_dust')
        .inputFluids('gtceu:cracked_aquatic_liquid 1000')
        .outputFluids('gtceu:aqua_gas 200')
        .blastFurnaceTemp(3200)
        .duration(1360)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor(('aquate_trichloride_dust'))
        .itemInputs('7x gtceu:cobalt_aquate_trichloride_dust', '2x gtceu:arsenic_dust')
        .itemOutputs('5x gtceu:aquate_trichloride_dust', '4x gtceu:cobalt_arsenide_dust')
        .duration(200)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor(('aquate_hydroxide_dust'))
        .itemInputs('5x gtceu:aquate_trichloride_dust')
        .itemOutputs('8x gtceu:aquate_hydroxide_dust')
        .inputFluids('minecraft:water 3000')
        .outputFluids('gtceu:hydrochloric_acid 3000')
        .duration(420)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor(('aquate_dust'))
        .itemInputs('8x gtceu:aquate_hydroxide_dust', '3x gtceu:sodium_dust')
        .itemOutputs('2x gtceu:aquate_dust', '9x gtceu:sodium_hydroxide_dust')
        .duration(1800)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.sifter(('filtered_prismarine_dust'))
        .itemInputs('5x gtceu:low_quality_prismarine_dust')
        .itemOutputs('3x gtceu:filtered_prismarine_dust')
        .chancedOutput('gtceu:phosphorus_dust', 800, 0)
        .chancedOutput('gtceu:calcium_dust', 500, 0)
        .chancedOutput('2x gtceu:bio_chaff', 500, 0)
        .duration(800)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.forge_hammer(('loosened_prismarine_dust'))
        .itemInputs('2x gtceu:filtered_prismarine_dust')
        .itemOutputs('3x gtceu:loosened_prismarine_dust')
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor(('prismarine_trisulfate_dust'))
        .itemInputs('4x gtceu:loosened_prismarine_dust', '21x gtceu:sodium_bisulfate_dust')
        .itemOutputs('5x gtceu:prismarine_trisulfate_dust', 'gtceu:sodium_dust')
        .outputFluids('gtceu:oxygen 3000')
        .duration(390)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor(('prismarine_trioxide_dust'))
        .itemInputs('5x gtceu:prismarine_trisulfate_dust')
        .itemOutputs('5x gtceu:prismarine_trioxide_dust')
        .inputFluids('minecraft:water 3000')
        .outputFluids('gtceu:sulfuric_acid 3000')
        .duration(220)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor(('dirty_prismarine_dust'))
        .itemInputs('5x gtceu:prismarine_trioxide_dust')
        .itemOutputs('9x gtceu:dirty_prismarine_dust')
        .inputFluids('gtceu:distilled_water 3000', 'gtceu:methanol 2000')
        .outputFluids('gtceu:hydrogen 2000')
        .duration(1450)
        .EUt(GTValues.VA[GTValues.EV])

        event.recipes.gtceu.electric_blast_furnace(('prismarine'))
        .itemInputs('gtceu:exquisite_dirty_prismarine_gem', 'gtceu:diamond_dust')
        .itemOutputs('3x minecraft:prismarine_shard', '2x minecraft:prismarine_crystals')
        .inputFluids('gtceu:crystaline_sea_water 360')
        .outputFluids('gtceu:carbon_monoxide 5000')
        .blastFurnaceTemp(3900)
        .duration(4670)
        .EUt(GTValues.VA[GTValues.IV])

        event.smelting('gtceu:prismarine_ingot', 'minecraft:prismarine_shard')

    event.recipes.gtceu.forming_press(('prismaric_cpu_wafer'))
        .itemInputs('gtceu:nano_cpu_wafer', '2x minecraft:prismarine_crystals')
        .itemOutputs('kubejs:prismaric_cpu_wafer')
        .duration(960)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.cutter(('prismaric_cpu_chip'))
        .itemInputs('kubejs:prismaric_cpu_wafer')
        .itemOutputs('6x kubejs:prismaric_cpu_chip')
        .inputFluids('gtceu:crystaline_sea_water 250')
        .duration(800)
        .EUt(GTValues.VA[GTValues.HV])

    event.remove({ id: 'gtceu:mixer/tungstensteel' })
    event.remove({ id: 'gtceu:centrifuge/decomposition_centrifuging__tungsten_steel' })
    event.recipes.gtceu.mixer(('prismaric_tungstensteel'))
        .itemInputs('gtceu:tungsten_dust', 'gtceu:steel_dust', 'minecraft:prismarine_shard')
        .itemOutputs('3x gtceu:tungsten_steel_dust')
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.centrifuge(('decomposition_centrifuging__prismaric_tungsten_steel'))
        .itemInputs('3x gtceu:tungsten_steel_dust')
        .itemOutputs('gtceu:tungsten_dust', 'gtceu:steel_dust', 'minecraft:prismarine_shard')
        .duration(913)
        .EUt(GTValues.VA[GTValues.LV])

    }
)