ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_reactor(('tellurium_dioxide_dust'))
        .itemInputs('gtceu:tellurium_dust')
        .inputFluids('gtceu:oxygen 2000')
        .itemOutputs('3x gtceu:tellurium_dioxide_dust')
        .duration(60)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor(('orthotelluric_acid'))
        .itemInputs('3x gtceu:tellurium_dioxide_dust')
        .inputFluids('gtceu:hydrogen_peroxide 1000', 'minecraft:water 2000')
        .outputFluids('gtceu:orthotelluric_acid 1000')
        .duration(180)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.dehydrator(('tellurium_hydroxide_dust'))
        .inputFluids('gtceu:orthotelluric_acid 1000')
        .outputFluids('minecraft:water 2500')
        .itemOutputs('3x gtceu:tellurium_hydroxide_dust')
        .duration(480)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor(('carbon_disulfide'))
        .itemInputs('gtceu:carbon_dust', '2x gtceu:sulfur_dust')
        .outputFluids('gtceu:carbon_disulfide 1000')
        .duration(20)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_plant(('diethylamine'))
        .inputFluids('gtceu:ammonia 1000', 'gtceu:ethanol 2000')
        .outputFluids('gtceu:diethylamine 1000')
        .duration(3600)
        .addCondition(GTNNRecipes.setPlantCasing(3))
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.large_chemical_reactor(('tellurium_diethyldithiocarbamate_dust'))
        .itemInputs('3x gtceu:tellurium_hydroxide_dust')
        .inputFluids('gtceu:carbon_disulfide 1000', 'gtceu:diethylamine 4000')
        .itemOutputs('73x gtceu:tellurium_diethyldithiocarbamate_dust')
        .duration(480)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.mixer(('rubber_mixture_dust'))
        .itemInputs('gtceu:silicone_rubber_dust', 'gtceu:styrene_butadiene_rubber_dust')
        .itemOutputs('2x gtceu:rubber_mixture_dust')
        .duration(230)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.electric_blast_furnace(('raw_curly_rubber_mixture_dust'))
        .itemInputs('8x gtceu:rubber_mixture_dust')
        .itemOutputs('3x gtceu:raw_curly_rubber_mixture_dust', 'gtceu:ash_dust')
        .circuit(1)
        .duration(8)
        .blastFurnaceTemp(5300)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.large_chemical_reactor(('tellurium_vulcanized_rubber'))
        .itemInputs('9x gtceu:raw_curly_rubber_mixture_dust', '8x gtceu:tellurium_diethyldithiocarbamate_dust', '1x gtceu:sulfur_dust')
        .outputFluids('gtceu:tellurium_vulcanized_rubber 1296')
        .duration(600)
        .EUt(GTValues.VA[GTValues.LuV])
    }
)