ServerEvents.recipes(event => {
    
    event.recipes.gtceu.mixer(('applidium'))
        .itemInputs('4x gtceu:ender_pearl_dust', '3x gtceu:lead_dust', 'gtceu:niobium_dust')
        .itemOutputs('10x gtceu:applidium_dust')
        .inputFluids('gtceu:mercury 2000')
        .duration(240)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.component_assembler(('item_cell_housing'))
        .itemInputs('2x gtceu:applidium_plate', '3x gtceu:aluminium_plate', '#gtceu:circuits/lv')
        .itemOutputs('ae2:item_cell_housing')
        .inputFluids('gtceu:polyethylene 288', 'gtceu:glass 144')
        .duration(240)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.component_assembler(('fluid_cell_housing'))
        .itemInputs('2x gtceu:double_applidium_plate', '3x gtceu:stainless_steel_plate', '#gtceu:circuits/hv')
        .itemOutputs('ae2:fluid_cell_housing')
        .inputFluids('gtceu:polytetrafluoroethylene 288', 'gtceu:glass 144')
        .duration(240)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.component_assembler(('cell_component_1k'))
        .itemInputs('ae2:logic_processor', '2x gtceu:applidium_plate', '2x #gtceu:circuits/lv', '4x #gtceu:circuits/ulv')
        .itemOutputs('ae2:cell_component_1k')
        .inputFluids('gtceu:soldering_alloy 144', 'gtceu:redstone 576')
        .duration(300)
        .EUt(GTValues.VA[GTValues.ULV])
        
    event.recipes.gtceu.component_assembler(('cell_component_4k'))
        .itemInputs('ae2:calculation_processor', '2x gtceu:applidium_plate', '2x #gtceu:circuits/mv', '4x #gtceu:circuits/lv')
        .itemOutputs('ae2:cell_component_4k')
        .inputFluids('gtceu:soldering_alloy 288', 'gtceu:glass 144')
        .duration(300)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.component_assembler(('cell_component_16k'))
        .itemInputs('ae2:calculation_processor', '2x gtceu:applidium_plate', '2x #gtceu:circuits/hv', '4x #gtceu:circuits/mv')
        .itemOutputs('ae2:cell_component_16k')
        .inputFluids('gtceu:soldering_alloy 288', 'gtceu:glass 144')
        .duration(300)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.component_assembler(('cell_component_64k'))
        .itemInputs('ae2:calculation_processor', '2x gtceu:applidium_plate', '2x #gtceu:circuits/ev', '4x #gtceu:circuits/hv')
        .itemOutputs('ae2:cell_component_64k')
        .inputFluids('gtceu:soldering_alloy 576', 'gtceu:glass 144')
        .duration(300)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.component_assembler(('cell_component_256k'))
        .itemInputs('ae2:calculation_processor', '2x gtceu:applidium_plate', '2x #gtceu:circuits/iv', '4x #gtceu:circuits/ev')
        .itemOutputs('ae2:cell_component_256k')
        .inputFluids('gtceu:soldering_alloy 576', 'gtceu:glass 144')
        .duration(300)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.wiremill(('quartz_fiber_from_certus_quartz'))
        .itemInputs('gtceu:certus_quartz_gem')
        .itemOutputs('ae2:quartz_fiber')
        .duration(300)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.wiremill(('quartz_fiber_from_quartzite'))
        .itemInputs('4x gtceu:quartzite_gem')
        .itemOutputs('ae2:quartz_fiber')
        .duration(300)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.wiremill(('quartz_fiber_from_quartz'))
        .itemInputs('2x minecraft:quartz')
        .itemOutputs('ae2:quartz_fiber')
        .duration(300)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.component_assembler(('semi_dark_monitor'))
        .itemInputs('3x gtceu:applidium_plate', '#gtceu:circuits/mv',)
        .itemOutputs('ae2:semi_dark_monitor')
        .inputFluids('gtceu:soldering_alloy 144', 'gtceu:glass 288', 'gtceu:redstone 288')
        .duration(300)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.component_assembler(('crafting_unit'))
        .itemInputs('8x gtceu:applidium_plate', 'ae2:logic_processor', '2x ae2:calculation_processor','2x #gtceu:circuits/hv', 'gtceu:hv_sensor', '4x #ae2:glass_cable')
        .itemOutputs('ae2:crafting_unit')
        .inputFluids('gtceu:soldering_alloy 144', 'gtceu:polyethylene 288')
        .duration(600)
        .EUt(GTValues.VA[GTValues.HV])

    }
)