ServerEvents.recipes(event => {
event.remove({ output: 'ae2:printed_calculation_processor' })
event.remove({ output: 'ae2:printed_engineering_processor' })
event.remove({ output: 'ae2:printed_logic_processor' })
event.remove({ output: 'ae2:printed_silicon' })
event.remove({ output: 'ae2:calculation_processor' })
event.remove({ output: 'ae2:engineering_processor' })
event.remove({ output: 'ae2:logic_processor' })
event.remove({ output: 'ae2:item_cell_housing' })
event.remove({ output: 'ae2:fluid_cell_housing' })
event.remove({ output: 'ae2:cell_component_1k' })
event.remove({ output: 'ae2:cell_component_4k' })
event.remove({ output: 'ae2:cell_component_16k' })
event.remove({ output: 'ae2:cell_component_64k' })
event.remove({ output: 'ae2:cell_component_256k' })
event.remove({ input: '#forge:ingots/iron', output: 'ae2:item_storage_cell_1k' })
event.remove({ input: '#forge:ingots/iron', output: 'ae2:item_storage_cell_4k' })
event.remove({ input: '#forge:ingots/iron', output: 'ae2:item_storage_cell_16k' })
event.remove({ input: '#forge:ingots/iron', output: 'ae2:item_storage_cell_64k' })
event.remove({ input: '#forge:ingots/iron', output: 'ae2:item_storage_cell_256k' })
event.remove({ input: '#forge:ingots/copper', output: 'ae2:fluid_storage_cell_1k' })
event.remove({ input: '#forge:ingots/copper', output: 'ae2:fluid_storage_cell_4k' })
event.remove({ input: '#forge:ingots/copper', output: 'ae2:fluid_storage_cell_16k' })
event.remove({ input: '#forge:ingots/copper', output: 'ae2:fluid_storage_cell_64k' })
event.remove({ input: '#forge:ingots/copper', output: 'ae2:fluid_storage_cell_256k' })
event.remove({ output: 'ae2:quartz_fiber' })
event.remove({ output: 'ae2:drive' })
event.remove({ input: '#forge:ingots/iron', output: 'ae2:semi_dark_monitor' })
event.remove({ output: 'ae2:terminal' })
event.remove({ output: 'ae2:crafting_terminal' })
event.remove({ output: 'ae2:pattern_encoding_terminal' })
event.remove({ output: 'ae2:molecular_assembler' })
event.remove({ output: 'ae2:crafting_unit' })
event.remove({ output: 'ae2:controller' })
event.remove({ input: '#forge:ingots/iron', output: 'ae2:pattern_provider' })
event.remove({ input: '#forge:ingots/iron', output: 'ae2:interface' })

    }
)