ServerEvents.recipes(event => {
    event.remove({ type: 'gtceu:electric_blast_furnace', output: 'gtceu:aluminium_nugget' })
    event.remove({ type: 'gtceu:alloy_smelter', output: 'gtceu:cupronickel_ingot' })
    event.remove({ id: 'gtceu:arc_furnace/arc_cupronickel_dust' })
    event.remove({ id: 'gtceu:extractor/extract_cupronickel_dust' })
    event.remove({ id: 'gtceu:smelting/smelt_dust_cupronickel_to_ingot' })
    event.remove({ type: 'gtceu:alloy_smelter', output: 'gtceu:brass_ingot' })
    event.remove({ id: 'gtceu:arc_furnace/arc_brass_dust' })
    event.remove({ id: 'gtceu:extractor/extract_brass_dust' })
    event.remove({ id: 'gtceu:smelting/smelt_dust_brass_to_ingot' })
    event.remove({ type: 'gtceu:alloy_smelter', output: 'gtceu:tin_alloy_ingot' })
    event.remove({ id: 'gtceu:arc_furnace/arc_tin_alloy_dust' })
    event.remove({ id: 'gtceu:extractor/extract_tin_alloy_dust' })
    event.remove({ id: 'gtceu:smelting/smelt_dust_tin_alloy_to_ingot' })
    event.remove({ id: 'gtceu:arc_furnace/arc_dense_red_alloy_manganese_phosphide_magnesium_diboride_mercury_barium_calcium_cuprate_uranium_triplatinum_samarium_iron_arsenic_oxide_lower_superconducting_alloy_plate' })
})