ServerEvents.tags('item', event => {
  event.add('gtceu:circuits/iv', 'kubejs:mutatedchip_processor')
  event.add('gtceu:circuits/zpm', 'kubejs:mutated_processor')
  event.add('gtceu:circuits/uv', 'kubejs:mutated_processor_assembly')
  event.add('gtceu:circuits/uhv', 'kubejs:mutated_processor_computer')
  event.add('gtceu:circuits/uev', 'kubejs:mutated_processor_mainframe')
  event.add('gtceu:circuits/uv', 'kubejs:null_processor')
  event.add('gtceu:circuits/uhv', 'kubejs:null_processor_assembly')
  event.add('gtceu:circuits/uev', 'kubejs:null_processor_computer')
  event.add('gtceu:circuits/uiv', 'kubejs:null_processor_mainframe')
  event.removeAllTagsFrom('gtnn:supracausal_processor')
  event.removeAllTagsFrom('gtnn:supracausal_assembly')
  event.removeAllTagsFrom('gtnn:supracausal_computer')
  event.removeAllTagsFrom('gtnn:supracausal_mainframe')
  event.removeAllTagsFrom('gtnn:cosmic_processor')
  event.removeAllTagsFrom('gtnn:cosmic_assembly')
  event.removeAllTagsFrom('gtnn:cosmic_computer')
  event.removeAllTagsFrom('gtnn:cosmic_mainframe')
  event.removeAllTagsFrom('gtnn:spintronic_processor')
  event.removeAllTagsFrom('gtnn:spintronic_assembly')
  event.removeAllTagsFrom('gtnn:spintronic_computer')
  event.removeAllTagsFrom('gtnn:spintronic_mainframe')
  event.removeAllTagsFrom('gtnn:optical_processor')
  event.removeAllTagsFrom('gtnn:optical_assembly')
  event.removeAllTagsFrom('gtnn:optical_computer')
  event.removeAllTagsFrom('gtnn:optical_mainframe')
  event.removeAllTagsFrom('gtnn:gooware_processor')
  event.removeAllTagsFrom('gtnn:gooware_assembly')
  event.removeAllTagsFrom('gtnn:gooware_computer')
  event.removeAllTagsFrom('gtnn:gooware_mainframe')
})