GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('time_machine')
        .category('time_machine')
        .setEUIO('in')
        .setMaxIOSize(2, 2, 2, 2)
        .setSlotOverlay(false, false, GuiTextures.COMPRESSOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_FUSION, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

})
GTCEuStartupEvents.registry('gtceu:machine', event => {
  event.create('time_machine', 'multiblock')
  .rotationState(RotationState.ALL)
  .recipeTypes('time_machine')
  .noRecipeModifier()
  .appearanceBlock(() => Block.getBlock('gtceu:high_power_casing'))
    .pattern(definition => FactoryBlockPattern.start()
        .aisle('             ', '             ', '             ', '             ', '             ', '             ', '             ', '             ', '             ', '             ', '     BBB     ', '             ', '             ', '             ', '             ')
        .aisle('             ', '             ', '             ', '             ', '             ', '             ', '             ', '             ', '             ', '   BBAAABB   ', '    D C D    ', '   BBAAABB   ', '             ', '             ', '             ')
        .aisle('             ', '             ', '             ', '             ', '             ', '             ', '             ', '             ', '  EAA   AAE  ', '  E  D D  E  ', '   AABBBAA   ', '  E  D D  E  ', '  EAA   AAE  ', '             ', '             ')
        .aisle('             ', '             ', '             ', '             ', '             ', '             ', '             ', '  A       A  ', ' B E     E B ', '  AEB   BEA  ', '      F      ', '  AEB    EA  ', ' B E     E B ', '  A       A  ', '             ')
        .aisle('     III     ', '             ', '             ', '             ', '             ', '             ', '             ', ' DA       AD ', ' B B     B B ', '  A   F   A  ', '             ', '  A       A  ', ' B B     B B ', ' DA       AD ', '     III     ')
        .aisle(' A  IIIII  A ', 'BGB   B   BHB', ' A         A ', '             ', '             ', '             ', ' A   BBB   A ', 'B B  BBB  B B', ' AD  BFB  DA ', '             ', '             ', '             ', ' AD       DA ', 'B B   B   B B', ' A  IIIII  A ')
        .aisle(' A  IIIII  A ', 'BCB  BDB  BCB', ' A    D    A ', '      D      ', '      D      ', '      D      ', ' A   BBB   A ', 'BCBFFFCFFFBCB', ' A   BBB   A ', '      D      ', '      D      ', '      D      ', ' A    D    A ', 'BCB  BDB  BCB', ' A  IIIII  A ')
        .aisle(' A  IIIII  A ', 'B B   B   B B', ' AD       DA ', '             ', '             ', '             ', ' AD  BFB  DA ', 'B B  B@B  B B', ' A   BBB   A ', '             ', '             ', '             ', ' A         A ', 'BJB   B   BKB', ' A  IIIII  A ')
        .aisle('     III     ', ' DA       AD ', ' B B     B B ', '  A       A  ', '             ', '  A   F   A  ', ' B B     B B ', ' DA       AD ', '             ', '             ', '             ', '             ', '             ', '             ', '     III     ')
        .aisle('             ', '  A       A  ', ' B E     E B ', '  AEB   BEA  ', '      F      ', '  AEB   BEA  ', ' B E     E B ', '  A       A  ', '             ', '             ', '             ', '             ', '             ', '             ', '             ')
        .aisle('             ', '             ', '  EAA   AAE  ', '  E  D D  E  ', '   AABBBAA   ', '  E  D D  E  ', '  EAA   AAE  ', '             ', '             ', '             ', '             ', '             ', '             ', '             ', '             ')
        .aisle('             ', '             ', '             ', '   BBAAABB   ', '    D C D    ', '   BBAAABB   ', '             ', '             ', '             ', '             ', '             ', '             ', '             ', '             ', '             ')
        .where('@', Predicates.controller(Predicates.blocks(definition.get())))
        .where('A', Predicates.blocks("gtceu:fusion_glass"))
        .where('B', Predicates.blocks("gtceu:computer_casing"))
        .where('C', Predicates.blocks("gtceu:superconducting_coil"))
        .where('D', Predicates.blocks("gtceu:high_power_casing"))
        .where('E', Predicates.blocks("gtceu:advanced_computer_casing"))
        .where('F', Predicates.blocks("gtceu:enriched_naquadah_frame"))
        .where('G', Predicates.abilities(PartAbility.EXPORT_ITEMS))
        .where('H', Predicates.abilities(PartAbility.IMPORT_FLUIDS))
        .where('I', Predicates.blocks("gtceu:computer_casing")
        .or(Predicates.abilities(PartAbility.INPUT_ENERGY))
        )
        .where('J', Predicates.abilities(PartAbility.IMPORT_ITEMS))
        .where('K', Predicates.abilities(PartAbility.EXPORT_FLUIDS))
        .build())
    .workableCasingModel("gtceu:block/casings/hpca/high_power_casing", 'gtceu:block/multiblock/fusion_reactor')
})
