StartupEvents.registry("item", event => {
  event.create("lv_certificate")
  event.create("mv_certificate")
  event.create("hv_certificate")
  event.create("ev_certificate")
  event.create("iv_certificate")
  event.create("luv_certificate")
  event.create("zpm_certificate")
  event.create("uv_certificate")
  event.create("uhv_certificate")
  event.create("universal_inscriber_press")
  event.create("mutagenic_light")

  event.create("luv_magnetic_core")
  event.create("luv_coil_cover")
  event.create("luv_regulation_part")
  event.create("luv_calculation_frame")
  event.create("luv_containment_forge_panel")
  event.create("luv_precision_assembly")
  event.create("luv_transportation_unit")
  event.create("luv_speed_rotation_engine")
  event.create("luv_quantum_power_core")

  event.create("zpm_magnetic_core")
  event.create("zpm_coil_cover")
  event.create("zpm_regulation_part")
  event.create("zpm_calculation_frame")
  event.create("zpm_containment_forge_panel")
  event.create("zpm_precision_assembly")
  event.create("zpm_transportation_unit")
  event.create("zpm_speed_rotation_engine")
  event.create("zpm_quantum_power_core")

  event.create("uv_magnetic_core")
  event.create("uv_coil_cover")
  event.create("uv_regulation_part")
  event.create("uv_calculation_frame")
  event.create("uv_containment_forge_panel")
  event.create("uv_precision_assembly")
  event.create("uv_transportation_unit")
  event.create("uv_speed_rotation_engine")
  event.create("uv_quantum_power_core")

  event.create("uhv_magnetic_core")
  event.create("uhv_coil_cover")
  event.create("uhv_regulation_part")
  event.create("uhv_calculation_frame")
  event.create("uhv_containment_forge_panel")
  event.create("uhv_precision_assembly")
  event.create("uhv_transportation_unit")
  event.create("uhv_speed_rotation_engine")
  event.create("uhv_quantum_power_core")
})